Endrer tekster fra Ditt NAV til Min side
navikt/veilarbdialog pull request #224
Opened 2022-11-25 08:12 UTC by lhartvik

2022-11-25 08:26 UTC, lhartvik commented
![](https://github.trello.services/images/mini-trello-icon.png) [Endre 'Ditt Nav' til 'Min Side' i brukernotifikasjon varslingstekster](https://trello.com/c/TqmbRKPW/674-endre-ditt-nav-til-min-side-i-brukernotifikasjon-varslingstekster)

2022-12-01 14:08 UTC, holymaloney commented
Standardtekster for ekstern varsling er dokumentert her: https://navikt.github.io/brukernotifikasjon-docs/eksternvarsling/

Dette er standardtekstene for sms- og epost-varsling for både beskjed og oppgave.
Hvis tekstene vi sender er like eller svært like standardtekstene, er det bedre at vi kun sender null i disse feltene når vi bestiller brukernotifikasjoner, slik at vi ikke trenger å gjøre noe neste gang nav trenger å endre disse.
Vi har vel noen caser i veilarbaktivitet der vi trenger custom varslingstekster (møtepåminnelse o.l), men her i dialog, ser det ut som vi ligger veldig tett på standardtekstene.

2022-12-07 13:10 UTC, holymaloney requested changes
Standardtekster for ekstern varsling er dokumentert her: https://navikt.github.io/brukernotifikasjon-docs/eksternvarsling/

Dette er standardtekstene for sms- og epost-varsling for både beskjed og oppgave.
Hvis tekstene vi sender er like eller svært like standardtekstene, er det bedre at vi kun sender null i disse feltene når vi bestiller brukernotifikasjoner, slik at vi ikke trenger å gjøre noe neste gang nav trenger å endre disse.
Vi har vel noen caser i veilarbaktivitet der vi trenger custom varslingstekster (møtepåminnelse o.l), men her i dialog, ser det ut som vi ligger veldig tett på standardtekstene.

2022-12-19 14:10 UTC, lhartvik commented
Må sjekke om alle er enig i at standardtekstene er gode nok for

- [ ] Beskjed sms-innhold
- [ ] Beskjed epost-tittel
- [ ] Beskjed epost-innhold
- [ ] Oppgave sms-innhold
- [ ] Oppgave epost-tittel
- [ ] Oppgave epost-innhold

2023-01-02 12:30 UTC, hakonph approved these changes

2023-01-02 12:59 UTC, holymaloney approved these changes

2023-01-02 13:50 UTC, merged